[env]
platform = atmelsam
board = mkrwifi1010
framework = arduino
monitor_speed = 115200
lib_deps =
    arduino-libraries/Arduino_MKRIoTCarrier
    arduino-libraries/WiFiNINA
    arduino-libraries/ArduinoMqttClient
    bblanchon/ArduinoJson

[env:kit_a]
build_flags = -DROLE_SENTINEL -DKIT_ID=\"kit_a\"

[env:kit_b]
build_flags = -DROLE_KEYPAD -DKIT_ID=\"kit_b\"
